# Generated by Django 3.1.2 on 2020-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('semester', models.DateField()),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.DateField()),
                ('professor_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('credit', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_semester_grade', models.PositiveSmallIntegerField()),
                ('budget', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
