# Generated by Django 3.1.3 on 2020-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='budget',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_semester_grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
